tlumok_version = '0.1.0'

[original_document]
path = './test-data/example-1.txt'
file_format = 'Txt'
[segments.segments.segment_0]
original_text = '''
Juvenes Translatores | EN -2020
'''
translated_text = '''
Juvenes Translatores | EN -2020
'''
checked = false

[segments.segments.segment_0.original_document_slice]
start = 0
len = 32

[segments.segments.segment_1]
original_text = '''
Archaeological report: Brussels, 8 May 2095
'''
translated_text = '''
Archaeological report: Brussels, 8 May 2095
'''
checked = false

[segments.segments.segment_1.original_document_slice]
start = 32
len = 44

[segments.segments.segment_2]
original_text = '''
Digital
'''
translated_text = '''
Digital
'''
checked = false

[segments.segments.segment_2.original_document_slice]
start = 76
len = 8

[segments.segments.segment_3]
original_text = ' archaeologists find occasional gems in the vast European information repository. '
translated_text = ' archaeologists find occasional gems in the vast European information repository. '
checked = false

[segments.segments.segment_3.original_document_slice]
start = 84
len = 82

[segments.segments.segment_4]
original_text = '''
Taken
'''
translated_text = '''
Taken
'''
checked = false

[segments.segments.segment_4.original_document_slice]
start = 166
len = 6

[segments.segments.segment_5]
original_text = '''
from the mountain of uncatalogued ephemera, this text is written in a style suggesting
'''
translated_text = '''
from the mountain of uncatalogued ephemera, this text is written in a style suggesting
'''
checked = false

[segments.segments.segment_5.original_document_slice]
start = 172
len = 87

[segments.segments.segment_6]
original_text = '''
composition in the early 21st century, possibly even on paper.
'''
translated_text = '''
composition in the early 21st century, possibly even on paper.
'''
checked = false

[segments.segments.segment_6.original_document_slice]
start = 259
len = 63

[segments.segments.segment_7]
original_text = '''
Diary fragment 1:
'''
translated_text = '''
Diary fragment 1:
'''
checked = false

[segments.segments.segment_7.original_document_slice]
start = 322
len = 18

[segments.segments.segment_8]
original_text = '''
Dear Diary,
'''
translated_text = '''
Dear Diary,
'''
checked = false

[segments.segments.segment_8.original_document_slice]
start = 340
len = 12

[segments.segments.segment_9]
original_text = 'Day 1 of our boating holiday on the Sûre in Luxembourg! '
translated_text = 'Day 1 of our boating holiday on the Sûre in Luxembourg! '
checked = false

[segments.segments.segment_9.original_document_slice]
start = 352
len = 57

[segments.segments.segment_10]
original_text = '''
Up at the crack of dawn to get to the
'''
translated_text = '''
Up at the crack of dawn to get to the
'''
checked = false

[segments.segments.segment_10.original_document_slice]
start = 409
len = 38

[segments.segments.segment_11]
original_text = 'departure point. '
translated_text = 'departure point. '
checked = false

[segments.segments.segment_11.original_document_slice]
start = 447
len = 17

[segments.segments.segment_12]
original_text = '''
Ten minutes to learn the ropes and then off we set in our canoes!
'''
translated_text = '''
Ten minutes to learn the ropes and then off we set in our canoes!
'''
checked = false

[segments.segments.segment_12.original_document_slice]
start = 464
len = 66

[segments.segments.segment_13]
original_text = '''
There was not a breath of wind as we drifted downstream, sometimes passing an angler staring
'''
translated_text = '''
There was not a breath of wind as we drifted downstream, sometimes passing an angler staring
'''
checked = false

[segments.segments.segment_13.original_document_slice]
start = 530
len = 93

[segments.segments.segment_14]
original_text = 'intently at his float, or a group of children paddling. '
translated_text = 'intently at his float, or a group of children paddling. '
checked = false

[segments.segments.segment_14.original_document_slice]
start = 623
len = 56

[segments.segments.segment_15]
original_text = '''
When I commented that the signs on the
'''
translated_text = '''
When I commented that the signs on the
'''
checked = false

[segments.segments.segment_15.original_document_slice]
start = 679
len = 39

[segments.segments.segment_16]
original_text = '''
two sides of the river looked like they were written in different languages, Dad grinned: “They’re
'''
translated_text = '''
two sides of the river looked like they were written in different languages, Dad grinned: “They’re
'''
checked = false

[segments.segments.segment_16.original_document_slice]
start = 718
len = 103

[segments.segments.segment_17]
original_text = 'two different countries – Germany on our left and Luxembourg on our right! '
translated_text = 'two different countries – Germany on our left and Luxembourg on our right! '
checked = false

[segments.segments.segment_17.original_document_slice]
start = 821
len = 77

[segments.segments.segment_18]
original_text = '''
We’re navigating
'''
translated_text = '''
We’re navigating
'''
checked = false

[segments.segments.segment_18.original_document_slice]
start = 898
len = 19

[segments.segments.segment_19]
original_text = '''
pretty much along the border!”
'''
translated_text = '''
pretty much along the border!”
'''
checked = false

[segments.segments.segment_19.original_document_slice]
start = 917
len = 33

[segments.segments.segment_20]
original_text = '''
Analytical note 1:
'''
translated_text = '''
Analytical note 1:
'''
checked = false

[segments.segments.segment_20.original_document_slice]
start = 950
len = 19

[segments.segments.segment_21]
original_text = '''
In this period, geographical information was provided in the form of metal panels or ‘signs’
'''
translated_text = '''
In this period, geographical information was provided in the form of metal panels or ‘signs’
'''
checked = false

[segments.segments.segment_21.original_document_slice]
start = 969
len = 97

[segments.segments.segment_22]
original_text = 'mounted on poles. '
translated_text = 'mounted on poles. '
checked = false

[segments.segments.segment_22.original_document_slice]
start = 1066
len = 18

[segments.segments.segment_23]
original_text = '''
Numerous examples can now be found in museums.
'''
translated_text = '''
Numerous examples can now be found in museums.
'''
checked = false

[segments.segments.segment_23.original_document_slice]
start = 1084
len = 47

[segments.segments.segment_24]
original_text = '''
Diary fragment 2:
'''
translated_text = '''
Diary fragment 2:
'''
checked = false

[segments.segments.segment_24.original_document_slice]
start = 1131
len = 18

[segments.segments.segment_25]
original_text = '''
I couldn’t get over that – I mean, if we want to go abroad we have to get on a plane or a ferry,
'''
translated_text = '''
I couldn’t get over that – I mean, if we want to go abroad we have to get on a plane or a ferry,
'''
checked = false

[segments.segments.segment_25.original_document_slice]
start = 1149
len = 101

[segments.segments.segment_26]
original_text = 'but here you can cross to another country without even having to show a passport. '
translated_text = 'but here you can cross to another country without even having to show a passport. '
checked = false

[segments.segments.segment_26.original_document_slice]
start = 1250
len = 82

[segments.segments.segment_27]
original_text = '''
The joy of
'''
translated_text = '''
The joy of
'''
checked = false

[segments.segments.segment_27.original_document_slice]
start = 1332
len = 11

[segments.segments.segment_28]
original_text = '''
Schengen!
'''
translated_text = '''
Schengen!
'''
checked = false

[segments.segments.segment_28.original_document_slice]
start = 1343
len = 10

[segments.segments.segment_29]
original_text = '''
Analytical note 2:
'''
translated_text = '''
Analytical note 2:
'''
checked = false

[segments.segments.segment_29.original_document_slice]
start = 1353
len = 19

[segments.segments.segment_30]
original_text = '''
Schengen was an early, and highly significant, stage in the dismantling of European border
'''
translated_text = '''
Schengen was an early, and highly significant, stage in the dismantling of European border
'''
checked = false

[segments.segments.segment_30.original_document_slice]
start = 1372
len = 91

[segments.segments.segment_31]
original_text = 'barriers. '
translated_text = 'barriers. '
checked = false

[segments.segments.segment_31.original_document_slice]
start = 1463
len = 10

[segments.segments.segment_32]
original_text = 'European union was long and complex, encountering frequent obstacles. '
translated_text = 'European union was long and complex, encountering frequent obstacles. '
checked = false

[segments.segments.segment_32.original_document_slice]
start = 1473
len = 70

[segments.segments.segment_33]
original_text = '''
Indeed many
'''
translated_text = '''
Indeed many
'''
checked = false

[segments.segments.segment_33.original_document_slice]
start = 1543
len = 12

[segments.segments.segment_34]
original_text = '''
predicted that it would not survive the Covid pandemic.
'''
translated_text = '''
predicted that it would not survive the Covid pandemic.
'''
checked = false

[segments.segments.segment_34.original_document_slice]
start = 1555
len = 56

[segments.segments.segment_35]
original_text = '''
Diary fragment 3:
'''
translated_text = '''
Diary fragment 3:
'''
checked = false

[segments.segments.segment_35.original_document_slice]
start = 1611
len = 18

[segments.segments.segment_36]
original_text = '''
After last night’s hotel (really scraping the bottom of the barrel!), I was prepared for the worst
'''
translated_text = '''
After last night’s hotel (really scraping the bottom of the barrel!), I was prepared for the worst
'''
checked = false

[segments.segments.segment_36.original_document_slice]
start = 1629
len = 101

[segments.segments.segment_37]
original_text = 'tonight, but I have my own room with its own bathroom and everything! '
translated_text = 'tonight, but I have my own room with its own bathroom and everything! '
checked = false

[segments.segments.segment_37.original_document_slice]
start = 1730
len = 70

[segments.segments.segment_38]
original_text = '''
In the lounge, I scraped
'''
translated_text = '''
In the lounge, I scraped
'''
checked = false

[segments.segments.segment_38.original_document_slice]
start = 1800
len = 25

[segments.segments.segment_39]
original_text = '''
together enough German to introduce myself to an Austrian group I met, and soon we were
'''
translated_text = '''
together enough German to introduce myself to an Austrian group I met, and soon we were
'''
checked = false

[segments.segments.segment_39.original_document_slice]
start = 1825
len = 88

[segments.segments.segment_40]
original_text = '''
chatting away nineteen to the dozen.
'''
translated_text = '''
chatting away nineteen to the dozen.
'''
checked = false

[segments.segments.segment_40.original_document_slice]
start = 1913
len = 37

[segments.segments.segment_41]
original_text = 'Dinner was hearty – fine by me as I had worked up a ravenous appetite. '
translated_text = 'Dinner was hearty – fine by me as I had worked up a ravenous appetite. '
checked = false

[segments.segments.segment_41.original_document_slice]
start = 1950
len = 73

[segments.segments.segment_42]
original_text = '''
But soon I felt my
'''
translated_text = '''
But soon I felt my
'''
checked = false

[segments.segments.segment_42.original_document_slice]
start = 2023
len = 19

[segments.segments.segment_43]
original_text = 'eyelids drooping and excused myself. '
translated_text = 'eyelids drooping and excused myself. '
checked = false

[segments.segments.segment_43.original_document_slice]
start = 2042
len = 37

[segments.segments.segment_44]
original_text = '''
So here I am, writing by the light of my bedside lamp,
'''
translated_text = '''
So here I am, writing by the light of my bedside lamp,
'''
checked = false

[segments.segments.segment_44.original_document_slice]
start = 2079
len = 55

[segments.segments.segment_45]
original_text = '''
looking forward to new adventures on the waterways of Europe tomorrow.
'''
translated_text = '''
looking forward to new adventures on the waterways of Europe tomorrow.
'''
checked = false

[segments.segments.segment_45.original_document_slice]
start = 2134
len = 71

[segments.segments.segment_46]
original_text = '''
Analytical note 3:
'''
translated_text = '''
Analytical note 3:
'''
checked = false

[segments.segments.segment_46.original_document_slice]
start = 2205
len = 19

[segments.segments.segment_47]
original_text = '''
For the unknown writer of this text, Schengen represented a way for holiday-makers to enjoy
'''
translated_text = '''
For the unknown writer of this text, Schengen represented a way for holiday-makers to enjoy
'''
checked = false

[segments.segments.segment_47.original_document_slice]
start = 2224
len = 92

[segments.segments.segment_48]
original_text = 'Europe’s rivers. '
translated_text = 'Europe’s rivers. '
checked = false

[segments.segments.segment_48.original_document_slice]
start = 2316
len = 19

[segments.segments.segment_49]
original_text = '''
Looking back on this tumultuous century, it is now clear that working in union
'''
translated_text = '''
Looking back on this tumultuous century, it is now clear that working in union
'''
checked = false

[segments.segments.segment_49.original_document_slice]
start = 2335
len = 79

[segments.segments.segment_50]
original_text = '''
was vital for European nations to face the challenges that lay ahead.
'''
translated_text = '''
was vital for European nations to face the challenges that lay ahead.
'''
checked = false

[segments.segments.segment_50.original_document_slice]
start = 2414
len = 70
